---
- hosts: [mesos_zookeepers]
  sudo: True
  roles:
    - { role: 'ansible-java8', tags: ['runtimes', 'java'], when: ansible_os_family == 'Debian' }
    - { role: 'ansible-zookeeper', zookeeper_hosts: "{{ groups.mesos_zookeepers}}", tags: ['zookeeper'] }

